export enum RoleName {
  SUPER_ADMIN_ROLE = 'SUPER ADMIN ROLE',
  ADMIN_ROLE = 'ADMIN ROLE',
  ACADEMIC_ROLE = 'ACADEMIC ROLE',
  LIBRARIAN_ROLE = 'LIBRARIAN ROLE',
  STUDENT_ROLE = 'STUDENT ROLE',
}
